# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='s', max_length=1),
        ),
    ]
